### ISSUE TITLE
Flask vulnerability in the Study Migration Tool

### ISSUE THREAD

**Issue by nmanchev** [dominodatalab/OpenSCE#2]
The version of Flask included in [requirements.txt](https://github.com/dominodatalab/OpenSCE/blob/main/study-migration-tool/requirements.txt) is vulnerable to possible disclosure of permanent session cookie as explained [here](https://github.com/dominodatalab/OpenSCE/security/dependabot/1). Can we please update it or if it isn't being used in the code remove it from requirements.txt?

**Comment by JonathanDeacon** [comment]
@nmanchev Thanks for raising that issue with Flask, I'll create a pull request to resolve it.
